#pragma once
#ifndef _DYNAMIK_SYSTEM_FLAGS_H
#define _DYNAMIK_SYSTEM_FLAGS_H

#define DMK_SUCCESSFUL		0
#define DMK_UNSUCCESSFUL	1

#define DMK_BOOTSTRAP_SUCCESSFUL	DMK_SUCCESSFUL
#define DMK_BOOTSTRAP_UNSUCCESSFUL	DMK_UNSUCCESSFUL
#define DMK_BOOTSTRAP_ERROR_INVALID 

#define DMK_INIT_SUCCESSFUL			DMK_SUCCESSFUL
#define DMK_INIT_UNSUCCESSFUL		DMK_UNSUCCESSFUL
#define DMK_INIT_LOAD_ERROR

#define DMK_CONFIG_SUCCESSFUL		DMK_SUCCESSFUL
#define DMK_CONFIG_UNSUCCESSFUL		DMK_UNSUCCESSFUL

enum class DMKSystemFlags {
	DMK_SYSTEM_UNSUCCESSFUL,
	DMK_SYSTEM_SUCCESSFUL,
};

#endif // !_DYNAMIK_SYSTEM_FLAGS_H
