#pragma once

#ifndef _DYNAMIK_CENTRAL_DATA_HUB_OBJECT_SPECIFICATIONS_H
#define _DYNAMIK_CENTRAL_DATA_HUB_OBJECT_SPECIFICATIONS_H

namespace Dynamik {
	// Object specifications:
	enum DMKObjectType {
		DMK_OBJECT_TYPE_STATIC_OBJECT = 0,
		DMK_OBJECT_TYPE_INTERACTIVE_OBJECT = 1,
		DMK_OBJECT_TYPE_PLAYER = 2,
		DMK_OBJECT_TYPE_NPC = 3,
		DMK_OBJECT_TYPE_AI = 4,
		DMK_OBJECT_TYPE_AUDIO = 5,
		DMK_OBJECT_TYPE_VIDEO = 6,
		DMK_OBJECT_TYPE_FONT = 7,
		DMK_OBJECT_TYPE_TEXTURE_UI = 8,
		DMK_OBJECT_TYPE_PARTICLE = 9,
		DMK_OBJECT_TYPE_SKYBOX = 10,
		DMK_OBJECT_TYPE_CAMERA = 11,
		DMK_OBJECT_TYPE_WIND = 12
	};

	enum DMKObjectDestructionType {
		DMK_OBJECT_DESTRUCTION_NONE = 0,
		DMK_OBJECT_DESTRUCTION_SOLID = 1,
		DMK_OBJECT_DESTRUCTION_LIQUID = 2,
		DMK_OBJECT_DESTRUCTION_PLASTIC = 3,
		DMK_OBJECT_DESTRUCTION_FRAGILE = 4,
		DMK_OBJECT_DESTRUCTION_WOOD = 5,
		DMK_OBJECT_DESTRUCTION_BLOCKS = 6,
		DMK_OBJECT_DESTRUCTION_PAPER = 7,
		DMK_OBJECT_DESTRUCTION_CUSTOM = 8
	};

	enum DMKObjectBehaviour {
		DMK_OBJECT_BEHAVIOUR_NONE = 0,
		DMK_OBJECT_BEHAVIOUR_DEFAULT = 1,
		DMK_OBJECT_BEHAVIOUR_SCRIPT = 2,
		DMK_OBJECT_BEHAVIOUR_EXPLOSIVE = 3,
		DMK_OBJECT_BEHAVIOUR_LIGHT = 4
	};

	enum DMKObjectTextureType {
		DMK_OBJECT_TEXTURE_TYPE_NONE = 0,
		DMK_OBJECT_TEXTURE_TYPE_2D_GREY = 1,
		DMK_OBJECT_TEXTURE_TYPE_2D_RGB = 2,
		DMK_OBJECT_TEXTURE_TYPE_2D_RGBA = 3,
		DMK_OBJECT_TEXTURE_TYPE_3D_GREY = 4,
		DMK_OBJECT_TEXTURE_TYPE_3D_RGB = 5,
		DMK_OBJECT_TEXTURE_TYPE_3D_RGBA = 6
	};

	// Audio specifications:
	enum DMKAudioOutputOptions {
		DMK_AUDIO_OUTPUT_DEFAULT = 0,
		DMK_AUDIO_OUTPUT_SPEAKERS_STERIO = 1,
		DMK_AUDIO_OUTPUT_SPEAKERS_MONO = 2,
		DMK_AUDIO_OUTPUT_SPEAKERS_LEFT = 3,
		DMK_AUDIO_OUTPUT_SPEAKERS_RIGHT = 4,
		DMK_AUDIO_OUTPUT_HEADPHONES_STERIO = 5,
		DMK_AUDIO_OUTPUT_HEADPHONES_MONO = 6,
		DMK_AUDIO_OUTPUT_HEADPHONES_LEFT = 7,
		DMK_AUDIO_OUTPUT_HEADPHONES_RIGHT = 8
	};

	enum DMKAudioPriorityOptions {
		DMK_AUDIO_PRIORITY_DEFAULT = 0,
		DMK_AUDIO_PRIORITY_LOW = 1,
		DMK_AUDIO_PRIORITY_HIGH = 2
	};

	// Camera specifications:
	enum DMKCameraType {
		DMK_CAMERA_TYPE_DEFAULT = 0,
		DMK_CAMERA_TYPE_ORTHOGRSPHIC = 1,
		DMK_CAMERA_TYPE_FRUSTUM = 2
	};

	// Lighting specifications:
	enum DMKLightingType {
		DMK_LIGHTING_TYPE_SPECULAR = 0,
		DMK_LIGHTING_TYPE_DIRECTIONAL = 1,
		DMK_LIGHTING_TYPE_EMISSIVE = 2
	};

	// Human Interfce Device(s) (HID) binding options:
	enum DMKHumanInterfaceDeviceBindingOptions {
		DMK_HID_KEY_BINDING_UNKNOWN = 0,
			
		DMK_HID_KEY_BINDING_MOUSE_BUTTON_RELEASE = 1,
		DMK_HID_KEY_BINDING_MOUSE_BUTTON_PRESS = 2,
		DMK_HID_KEY_BINDING_MOUSE_BUTTON_REPEAT = 3,
			
		DMK_HID_KEY_BINDING_HAT_CENTERED = 4,
		DMK_HID_KEY_BINDING_HAT_UP = 5,
		DMK_HID_KEY_BINDING_HAT_RIGHT = 6,
		DMK_HID_KEY_BINDING_HAT_DOWN = 7,
		DMK_HID_KEY_BINDING_HAT_LEFT = 8,
		DMK_HID_KEY_BINDING_HAT_RIGHT_UP = 9,
		DMK_HID_KEY_BINDING_HAT_RIGHT_DOWN = 10,
		DMK_HID_KEY_BINDING_HAT_LEFT_UP = 11,
		DMK_HID_KEY_BINDING_HAT_LEFT_DOWN = 12,
			
		DMK_HID_KEY_SPACE = 13,
		DMK_HID_KEY_APOSTROPHE = 14,
		DMK_HID_KEY_COMA = 15,
		DMK_HID_KEY_MINUS = 16,
		DMK_HID_KEY_PERIOD = 17,
		DMK_HID_KEY_SLASH = 18,
		DMK_HID_KEY_0 = 19,
		DMK_HID_KEY_1 = 20,
		DMK_HID_KEY_2 = 21,
		DMK_HID_KEY_3 = 22,
		DMK_HID_KEY_4 = 23,
		DMK_HID_KEY_5 = 24,
		DMK_HID_KEY_6 = 25,
		DMK_HID_KEY_7 = 26,
		DMK_HID_KEY_8 = 27,
		DMK_HID_KEY_9 = 28,
			
		DMK_HID_KEY_SEMICOLON = 29,
		DMK_HID_KEY_EQUAL = 30,
			
		DMK_HID_KEY_A = 31,
		DMK_HID_KEY_B = 32,
		DMK_HID_KEY_C = 33,
		DMK_HID_KEY_D = 34,
		DMK_HID_KEY_E = 35,
		DMK_HID_KEY_F = 36,
		DMK_HID_KEY_G = 37,
		DMK_HID_KEY_H = 38,
		DMK_HID_KEY_I = 39,
		DMK_HID_KEY_J = 40,
		DMK_HID_KEY_K = 41,
		DMK_HID_KEY_L = 42,
		DMK_HID_KEY_M = 43,
		DMK_HID_KEY_N = 44,
		DMK_HID_KEY_O = 45,
		DMK_HID_KEY_P = 46,
		DMK_HID_KEY_Q = 47,
		DMK_HID_KEY_R = 48,
		DMK_HID_KEY_S = 49,
		DMK_HID_KEY_T = 50,
		DMK_HID_KEY_U = 51,
		DMK_HID_KEY_V = 52,
		DMK_HID_KEY_W = 53,
		DMK_HID_KEY_X = 54,
		DMK_HID_KEY_Y = 55,
		DMK_HID_KEY_Z = 56,
			
		DMK_HID_KEY_LEFT_BRACKET = 57,
		DMK_HID_KEY_BACKLASH = 58,
		DMK_HID_KEY_RIGHT_BRACKET = 59,
		DMK_HID_KEY_RIGHT_GRAVE_ACCENT = 60,
		DMK_HID_KEY_WORLD_1 = 60,
		DMK_HID_KEY_WORLD_2 = 61,
			
		DMK_HID_KEY_ESCAPE = 62,
		DMK_HID_KEY_ENTER = 63,
		DMK_HID_KEY_TAB = 64,
		DMK_HID_KEY_BACKSPACE = 65,
		DMK_HID_KEY_INSERT = 67,
		DMK_HID_KEY_DELETE = 68,
		DMK_HID_KEY_RIGHT = 69,
		DMK_HID_KEY_LEFT = 70,
		DMK_HID_KEY_DOWN = 71,
		DMK_HID_KEY_UP = 72,
		DMK_HID_KEY_PAGE_UP = 73,
		DMK_HID_KEY_PAGE_DOWN = 74,
		DMK_HID_KEY_HOME = 75,
		DMK_HID_KEY_END = 76,
		DMK_HID_KEY_CAPS_LOCK = 77,
		DMK_HID_KEY_SCROLL_LOCK = 78,
		DMK_HID_KEY_NUM_LOCK = 79,
		DMK_HID_KEY_PRINT_SCREEN = 80,
		DMK_HID_KEY_PAUSE = 81,
			
		DMK_HID_KEY_F1 = 82,
		DMK_HID_KEY_F2 = 83,
		DMK_HID_KEY_F3 = 84,
		DMK_HID_KEY_F4 = 85,
		DMK_HID_KEY_F5 = 86,
		DMK_HID_KEY_F6 = 87,
		DMK_HID_KEY_F7 = 88,
		DMK_HID_KEY_F8 = 89,
		DMK_HID_KEY_F9 = 90,
		DMK_HID_KEY_F10 = 91,
		DMK_HID_KEY_F11 = 92,
		DMK_HID_KEY_F12 = 93,
		DMK_HID_KEY_F13 = 94,
		DMK_HID_KEY_F14 = 95,
		DMK_HID_KEY_F15 = 96,
		DMK_HID_KEY_F16 = 97,
		DMK_HID_KEY_F17 = 98,
		DMK_HID_KEY_F18 = 99,
		DMK_HID_KEY_F19 = 100,
		DMK_HID_KEY_F20 = 101,
		DMK_HID_KEY_F21 = 102,
		DMK_HID_KEY_F22 = 103,
		DMK_HID_KEY_F23 = 104,
		DMK_HID_KEY_F24 = 105,
		DMK_HID_KEY_F25 = 106,
			
		DMK_HID_KEY_KP_0 = 107,
		DMK_HID_KEY_KP_1 = 108,
		DMK_HID_KEY_KP_2 = 109,
		DMK_HID_KEY_KP_3 = 110,
		DMK_HID_KEY_KP_4 = 111,
		DMK_HID_KEY_KP_5 = 112,
		DMK_HID_KEY_KP_6 = 113,
		DMK_HID_KEY_KP_7 = 114,
		DMK_HID_KEY_KP_8 = 115,
		DMK_HID_KEY_KP_9 = 116,
		DMK_HID_KEY_KP_DECIMAL = 117,
		DMK_HID_KEY_KP_DIVIDE = 118,
		DMK_HID_KEY_KP_MULTIPLY = 119,
		DMK_HID_KEY_KP_SUBTRACT = 120,
		DMK_HID_KEY_KP_ADD = 121,
		DMK_HID_KEY_KP_ENTER = 122,
		DMK_HID_KEY_KP_EQUAL = 123,
			
		DMK_HID_KEY_LEFT_SHIFT = 124,
		DMK_HID_KEY_LEFT_CONTROL = 125,
		DMK_HID_KEY_LEFT_ALT = 126,
		DMK_HID_KEY_LEFT_SUPER = 127,
			
		DMK_HID_KEY_RIGHT_SHIFT = 128,
		DMK_HID_KEY_RIGHT_CONTROL = 129,
		DMK_HID_KEY_RIGHT_ALT = 130,
		DMK_HID_KEY_RIGHT_SUPER = 131,
			
		DMK_HID_KEY_MENU = 132,
		DMK_HID_KEY_LAST = 133,
			
		DMK_HID_MOD_SHIFT = 134,
		DMK_HID_MOD_CONTROL = 135,
		DMK_HID_MOD_ALT = 136,
		DMK_HID_MOD_SUPER = 137,
		DMK_HID_MOD_CAPS_LOCK = 138,
		DMK_HID_MOD_NUM_LOCK = 139,
			
		DMK_HID_MOUSE_BUTTON_1 = 140,
		DMK_HID_MOUSE_BUTTON_2 = 141,
		DMK_HID_MOUSE_BUTTON_3 = 142,
		DMK_HID_MOUSE_BUTTON_4 = 143,
		DMK_HID_MOUSE_BUTTON_5 = 144,
		DMK_HID_MOUSE_BUTTON_6 = 145,
		DMK_HID_MOUSE_BUTTON_7 = 146,
		DMK_HID_MOUSE_BUTTON_8 = 147,
		DMK_HID_MOUSE_BUTTON_LAST = 148,
		DMK_HID_MOUSE_BUTTON_LEFT = 149,
		DMK_HID_MOUSE_BUTTON_RIGHT = 150,
		DMK_HID_MOUSE_BUTTON_MIDDLE = 151,
			
		DMK_HID_JOYSTICK_1 = 152,
		DMK_HID_JOYSTICK_2 = 153,
		DMK_HID_JOYSTICK_3 = 154,
		DMK_HID_JOYSTICK_4 = 155,
		DMK_HID_JOYSTICK_5 = 156,
		DMK_HID_JOYSTICK_6 = 157,
		DMK_HID_JOYSTICK_7 = 158,
		DMK_HID_JOYSTICK_8 = 159,
		DMK_HID_JOYSTICK_9 = 160,
		DMK_HID_JOYSTICK_10 = 161,
		DMK_HID_JOYSTICK_11 = 162,
		DMK_HID_JOYSTICK_12 = 163,
		DMK_HID_JOYSTICK_13 = 164,
		DMK_HID_JOYSTICK_14 = 165,
		DMK_HID_JOYSTICK_15 = 166,
		DMK_HID_JOYSTICK_16 = 167,
			
		DMK_HID_GAMEPAD_BUTTON_A = 168,
		DMK_HID_GAMEPAD_BUTTON_B = 169,
		DMK_HID_GAMEPAD_BUTTON_X = 170,
		DMK_HID_GAMEPAD_BUTTON_Y = 171,
		DMK_HID_GAMEPAD_BUTTON_LEFT_BUMPER = 172,
		DMK_HID_GAMEPAD_BUTTON_RIGHT_BUMPER = 173,
		DMK_HID_GAMEPAD_BUTTON_BACK = 174,
		DMK_HID_GAMEPAD_BUTTON_START = 175,
		DMK_HID_GAMEPAD_BUTTON_GUIDE = 176,
		DMK_HID_GAMEPAD_BUTTON_LEFT_THUMB = 177,
		DMK_HID_GAMEPAD_BUTTON_RIGHT_THUMB = 178,
		DMK_HID_GAMEPAD_BUTTON_DPAD_UP = 179,
		DMK_HID_GAMEPAD_BUTTON_DPAD_RIGHT = 180,
		DMK_HID_GAMEPAD_BUTTON_DPAD_DOWN = 181,
		DMK_HID_GAMEPAD_BUTTON_DPAD_LEFT = 182,
		DMK_HID_GAMEPAD_BUTTON_LAST = 183,
			
		DMK_HID_GAMEPAD_BUTTON_CROSS = 184,
		DMK_HID_GAMEPAD_BUTTON_CIRCLE = 185,
		DMK_HID_GAMEPAD_BUTTON_SQUARE = 186,
		DMK_HID_GAMEPAD_BUTTON_TRIANGLE = 187,
			
		DMK_HID_GAMEPAD_AXIS_LEFT_X = 188,
		DMK_HID_GAMEPAD_AXIS_LEFT_Y = 189,
		DMK_HID_GAMEPAD_AXIS_RIGHT_X = 190,
		DMK_HID_GAMEPAD_AXIS_RIGHT_Y = 191,
		DMK_HID_GAMEPAD_AXIS_LEFT_TRIGGER = 192,
		DMK_HID_GAMEPAD_AXIS_RIGHT_TRIGGER = 193,
		DMK_HID_GAMEPAD_AXIS_LAST = 194,

		DMK_HID_UNKNOWN = 195
	};
}

#endif // !_DYNAMIK_CENTRAL_DATA_HUB_OBJECT_SPECIFICATIONS_H
