#pragma once

#ifndef _DYNAMIK_CENTRAL_DATA_HUB_OBJECT_SPECIFICATIONS_H
#define _DYNAMIK_CENTRAL_DATA_HUB_OBJECT_SPECIFICATIONS_H

namespace Dynamik {
	/* OBJECT SPECIFICATIONS */
	// Main object types:
	enum DMKMainObjectTypes {
		DMK_RENDERABLE_OBJECT = 0,
		DMK_NONE_RENDERABLE_OBJECT = 1,
		DMK_SCRIPT_FILE = 2,
		DMK_AI_OBJECT = 3
	};

	// Object types:
	enum DMKObjectType {
		DMK_OBJECT_TYPE_STATIC_OBJECT = 0,
		DMK_OBJECT_TYPE_INTERACTIVE_OBJECT = 1,
		DMK_OBJECT_TYPE_PLAYER = 2,
		DMK_OBJECT_TYPE_NPC = 3,
		DMK_OBJECT_TYPE_AI = 4,
		DMK_OBJECT_TYPE_AUDIO = 5,
		DMK_OBJECT_TYPE_VIDEO = 6,
		DMK_OBJECT_TYPE_FONT = 7,
		DMK_OBJECT_TYPE_TEXTURE_UI = 8,
		DMK_OBJECT_TYPE_PARTICLE = 9,
		DMK_OBJECT_TYPE_SKYBOX = 10,
		DMK_OBJECT_TYPE_CAMERA = 11,
		DMK_OBJECT_TYPE_WIND = 12
	};

	// Destruction types:
	enum DMKObjectDestructionType {
		DMK_OBJECT_DESTRUCTION_NONE = 0,
		DMK_OBJECT_DESTRUCTION_SOLID = 1,
		DMK_OBJECT_DESTRUCTION_LIQUID = 2,
		DMK_OBJECT_DESTRUCTION_PLASTIC = 3,
		DMK_OBJECT_DESTRUCTION_FRAGILE = 4,
		DMK_OBJECT_DESTRUCTION_WOOD = 5,
		DMK_OBJECT_DESTRUCTION_BLOCKS = 6,
		DMK_OBJECT_DESTRUCTION_PAPER = 7,
		DMK_OBJECT_DESTRUCTION_CUSTOM = 8
	};

	// Object behaviours:
	enum DMKObjectBehaviour {
		DMK_OBJECT_BEHAVIOUR_NONE = 0,
		DMK_OBJECT_BEHAVIOUR_DEFAULT = 1,
		DMK_OBJECT_BEHAVIOUR_SCRIPT = 2,
		DMK_OBJECT_BEHAVIOUR_EXPLOSIVE = 3,
		DMK_OBJECT_BEHAVIOUR_LIGHT = 4
	};

	// Texture types:
	enum DMKObjectTextureType {
		DMK_OBJECT_TEXTURE_TYPE_NONE = 0,
		DMK_OBJECT_TEXTURE_TYPE_2D_GREY = 1,
		DMK_OBJECT_TEXTURE_TYPE_2D_RGB = 2,
		DMK_OBJECT_TEXTURE_TYPE_2D_RGBA = 3,
		DMK_OBJECT_TEXTURE_TYPE_3D_GREY = 4,
		DMK_OBJECT_TEXTURE_TYPE_3D_RGB = 5,
		DMK_OBJECT_TEXTURE_TYPE_3D_RGBA = 6
	};

	/* AUDIO SPECIFICATIONS */
	// Output options:
	enum DMKAudioOutputOptions {
		DMK_AUDIO_OUTPUT_DEFAULT = 0,
		DMK_AUDIO_OUTPUT_SPEAKERS_STERIO = 1,
		DMK_AUDIO_OUTPUT_SPEAKERS_MONO = 2,
		DMK_AUDIO_OUTPUT_SPEAKERS_LEFT = 3,
		DMK_AUDIO_OUTPUT_SPEAKERS_RIGHT = 4,
		DMK_AUDIO_OUTPUT_HEADPHONES_STERIO = 5,
		DMK_AUDIO_OUTPUT_HEADPHONES_MONO = 6,
		DMK_AUDIO_OUTPUT_HEADPHONES_LEFT = 7,
		DMK_AUDIO_OUTPUT_HEADPHONES_RIGHT = 8
	};

	// Priority options:
	enum DMKAudioPriorityOptions {
		DMK_AUDIO_PRIORITY_DEFAULT = 0,
		DMK_AUDIO_PRIORITY_LOW = 1,
		DMK_AUDIO_PRIORITY_HIGH = 2
	};

	/* CAMERA SPECIFICATIONS */
	// Camera types:
	enum DMKCameraType {
		DMK_CAMERA_TYPE_DEFAULT = 0,
		DMK_CAMERA_TYPE_ORTHOGRSPHIC = 1,
		DMK_CAMERA_TYPE_FRUSTUM = 2
	};

	/* LIGHTING SPECIFICATIONS */
	// Lighting types:
	enum DMKLightingType {
		DMK_LIGHTING_TYPE_SPECULAR = 0,
		DMK_LIGHTING_TYPE_DIRECTIONAL = 1,
		DMK_LIGHTING_TYPE_EMISSIVE = 2
	};

	/* KEY BINDINGS */
	// Human Interfce Device(s) (HID) binding options:
	enum class DMKHumanInterfaceDeviceBindingOptions {
		DMK_HID_UNKNOWN,
		DMK_HID_KEY_BINDING_UNKNOWN,

		DMK_HID_KEY_BINDING_MOUSE_BUTTON_RELEASE,
		DMK_HID_KEY_BINDING_MOUSE_BUTTON_PRESS,
		DMK_HID_KEY_BINDING_MOUSE_BUTTON_REPEAT,

		DMK_HID_KEY_BINDING_HAT_CENTERED,
		DMK_HID_KEY_BINDING_HAT_UP,
		DMK_HID_KEY_BINDING_HAT_RIGHT,
		DMK_HID_KEY_BINDING_HAT_DOWN,
		DMK_HID_KEY_BINDING_HAT_LEFT,
		DMK_HID_KEY_BINDING_HAT_RIGHT_UP,
		DMK_HID_KEY_BINDING_HAT_RIGHT_DOWN,
		DMK_HID_KEY_BINDING_HAT_LEFT_UP,
		DMK_HID_KEY_BINDING_HAT_LEFT_DOWN,

		DMK_HID_KEY_SPACE,
		DMK_HID_KEY_APOSTROPHE,
		DMK_HID_KEY_COMA,
		DMK_HID_KEY_MINUS,
		DMK_HID_KEY_PERIOD,
		DMK_HID_KEY_SLASH,
		DMK_HID_KEY_0,
		DMK_HID_KEY_1,
		DMK_HID_KEY_2,
		DMK_HID_KEY_3,
		DMK_HID_KEY_4,
		DMK_HID_KEY_5,
		DMK_HID_KEY_6,
		DMK_HID_KEY_7,
		DMK_HID_KEY_8,
		DMK_HID_KEY_9,
		DMK_HID_KEY_SEMICOLON,
		DMK_HID_KEY_EQUAL,
		DMK_HID_KEY_A,
		DMK_HID_KEY_B,
		DMK_HID_KEY_C,
		DMK_HID_KEY_D,
		DMK_HID_KEY_E,
		DMK_HID_KEY_F,
		DMK_HID_KEY_G,
		DMK_HID_KEY_H,
		DMK_HID_KEY_I,
		DMK_HID_KEY_J,
		DMK_HID_KEY_K,
		DMK_HID_KEY_L,
		DMK_HID_KEY_M,
		DMK_HID_KEY_N,
		DMK_HID_KEY_O,
		DMK_HID_KEY_P,
		DMK_HID_KEY_Q,
		DMK_HID_KEY_R,
		DMK_HID_KEY_S,
		DMK_HID_KEY_T,
		DMK_HID_KEY_U,
		DMK_HID_KEY_V,
		DMK_HID_KEY_W,
		DMK_HID_KEY_X,
		DMK_HID_KEY_Y,
		DMK_HID_KEY_Z,
		DMK_HID_KEY_LEFT_BRACKET,
		DMK_HID_KEY_BACKLASH,
		DMK_HID_KEY_RIGHT_BRACKET,
		DMK_HID_KEY_RIGHT_GRAVE_ACCENT,
		DMK_HID_KEY_WORLD_1,
		DMK_HID_KEY_WORLD_2,
		DMK_HID_KEY_ESCAPE,
		DMK_HID_KEY_ENTER,
		DMK_HID_KEY_TAB,
		DMK_HID_KEY_BACKSPACE,
		DMK_HID_KEY_INSERT,
		DMK_HID_KEY_DELETE,
		DMK_HID_KEY_RIGHT,
		DMK_HID_KEY_LEFT,
		DMK_HID_KEY_DOWN,
		DMK_HID_KEY_UP,
		DMK_HID_KEY_PAGE_UP,
		DMK_HID_KEY_PAGE_DOWN,
		DMK_HID_KEY_HOME,
		DMK_HID_KEY_END,
		DMK_HID_KEY_CAPS_LOCK,
		DMK_HID_KEY_SCROLL_LOCK,
		DMK_HID_KEY_NUM_LOCK,
		DMK_HID_KEY_PRINT_SCREEN,
		DMK_HID_KEY_PAUSE,
		DMK_HID_KEY_F1,
		DMK_HID_KEY_F2,
		DMK_HID_KEY_F3,
		DMK_HID_KEY_F4,
		DMK_HID_KEY_F5,
		DMK_HID_KEY_F6,
		DMK_HID_KEY_F7,
		DMK_HID_KEY_F8,
		DMK_HID_KEY_F9,
		DMK_HID_KEY_F10,
		DMK_HID_KEY_F11,
		DMK_HID_KEY_F12,
		DMK_HID_KEY_F13,
		DMK_HID_KEY_F14,
		DMK_HID_KEY_F15,
		DMK_HID_KEY_F16,
		DMK_HID_KEY_F17,
		DMK_HID_KEY_F18,
		DMK_HID_KEY_F19,
		DMK_HID_KEY_F20,
		DMK_HID_KEY_F21,
		DMK_HID_KEY_F22,
		DMK_HID_KEY_F23,
		DMK_HID_KEY_F24,
		DMK_HID_KEY_F25,
		DMK_HID_KEY_KP_0,
		DMK_HID_KEY_KP_1,
		DMK_HID_KEY_KP_2,
		DMK_HID_KEY_KP_3,
		DMK_HID_KEY_KP_4,
		DMK_HID_KEY_KP_5,
		DMK_HID_KEY_KP_6,
		DMK_HID_KEY_KP_7,
		DMK_HID_KEY_KP_8,
		DMK_HID_KEY_KP_9,
		DMK_HID_KEY_KP_DECIMAL,
		DMK_HID_KEY_KP_DIVIDE,
		DMK_HID_KEY_KP_MULTIPLY,
		DMK_HID_KEY_KP_SUBTRACT,
		DMK_HID_KEY_KP_ADD,
		DMK_HID_KEY_KP_ENTER,
		DMK_HID_KEY_KP_EQUAL,
		DMK_HID_KEY_LEFT_SHIFT,
		DMK_HID_KEY_LEFT_CONTROL,
		DMK_HID_KEY_LEFT_ALT,
		DMK_HID_KEY_LEFT_SUPER,
		DMK_HID_KEY_RIGHT_SHIFT,
		DMK_HID_KEY_RIGHT_CONTROL,
		DMK_HID_KEY_RIGHT_ALT,
		DMK_HID_KEY_RIGHT_SUPER,
		DMK_HID_KEY_MENU,
		DMK_HID_KEY_LAST,

		DMK_HID_MOD_SHIFT,
		DMK_HID_MOD_CONTROL,
		DMK_HID_MOD_ALT,
		DMK_HID_MOD_SUPER,
		DMK_HID_MOD_CAPS_LOCK,
		DMK_HID_MOD_NUM_LOCK,

		DMK_HID_MOUSE_BUTTON_1,
		DMK_HID_MOUSE_BUTTON_2,
		DMK_HID_MOUSE_BUTTON_3,
		DMK_HID_MOUSE_BUTTON_4,
		DMK_HID_MOUSE_BUTTON_5,
		DMK_HID_MOUSE_BUTTON_6,
		DMK_HID_MOUSE_BUTTON_7,
		DMK_HID_MOUSE_BUTTON_8,
		DMK_HID_MOUSE_BUTTON_LAST,
		DMK_HID_MOUSE_BUTTON_LEFT,
		DMK_HID_MOUSE_BUTTON_RIGHT,
		DMK_HID_MOUSE_BUTTON_MIDDLE,

		DMK_HID_JOYSTICK_1,
		DMK_HID_JOYSTICK_2,
		DMK_HID_JOYSTICK_3,
		DMK_HID_JOYSTICK_4,
		DMK_HID_JOYSTICK_5,
		DMK_HID_JOYSTICK_6,
		DMK_HID_JOYSTICK_7,
		DMK_HID_JOYSTICK_8,
		DMK_HID_JOYSTICK_9,
		DMK_HID_JOYSTICK_10,
		DMK_HID_JOYSTICK_11,
		DMK_HID_JOYSTICK_12,
		DMK_HID_JOYSTICK_13,
		DMK_HID_JOYSTICK_14,
		DMK_HID_JOYSTICK_15,
		DMK_HID_JOYSTICK_16,

		DMK_HID_GAMEPAD_BUTTON_A,
		DMK_HID_GAMEPAD_BUTTON_B,
		DMK_HID_GAMEPAD_BUTTON_X,
		DMK_HID_GAMEPAD_BUTTON_Y,
		DMK_HID_GAMEPAD_BUTTON_LEFT_BUMPER,
		DMK_HID_GAMEPAD_BUTTON_RIGHT_BUMPER,
		DMK_HID_GAMEPAD_BUTTON_BACK,
		DMK_HID_GAMEPAD_BUTTON_START,
		DMK_HID_GAMEPAD_BUTTON_GUIDE,
		DMK_HID_GAMEPAD_BUTTON_LEFT_THUMB,
		DMK_HID_GAMEPAD_BUTTON_RIGHT_THUMB,
		DMK_HID_GAMEPAD_BUTTON_DPAD_UP,
		DMK_HID_GAMEPAD_BUTTON_DPAD_RIGHT,
		DMK_HID_GAMEPAD_BUTTON_DPAD_DOWN,
		DMK_HID_GAMEPAD_BUTTON_DPAD_LEFT,
		DMK_HID_GAMEPAD_BUTTON_LAST,

		DMK_HID_GAMEPAD_BUTTON_CROSS,
		DMK_HID_GAMEPAD_BUTTON_CIRCLE,
		DMK_HID_GAMEPAD_BUTTON_SQUARE,
		DMK_HID_GAMEPAD_BUTTON_TRIANGLE,

		DMK_HID_GAMEPAD_AXIS_LEFT_X,
		DMK_HID_GAMEPAD_AXIS_LEFT_Y,
		DMK_HID_GAMEPAD_AXIS_RIGHT_X,
		DMK_HID_GAMEPAD_AXIS_RIGHT_Y,
		DMK_HID_GAMEPAD_AXIS_LEFT_TRIGGER,
		DMK_HID_GAMEPAD_AXIS_RIGHT_TRIGGER,
		DMK_HID_GAMEPAD_AXIS_LAST
	};
}

#endif // !_DYNAMIK_CENTRAL_DATA_HUB_OBJECT_SPECIFICATIONS_H
