#pragma once
#ifndef _DYNAMIK_RENDERING_SPECIFICATIONS_H
#define _DYNAMIK_RENDERING_SPECIFICATIONS_H

namespace Dynamik {
	enum class DMKPipelineTopology {
		DMK_PIPELINE_TOPOLOGY_POINT,
		DMK_PIPELINE_TOPOLOGY_LINE_LIST,
		DMK_PIPELINE_TOPOLOGY_LINE_STRIP,
		DMK_PIPELINE_TOPOLOGY_TRIANGLE_LIST,
		DMK_PIPELINE_TOPOLOGY_TRIANGLE_STRIP,
		DMK_PIPELINE_TOPOLOGY_TRIANGLE_FAN,
		DMK_PIPELINE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY,
		DMK_PIPELINE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY,
		DMK_PIPELINE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY,
		DMK_PIPELINE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY,
		DMK_PIPELINE_TOPOLOGY_PATCH_LIST,
	};

	enum class DMKPipelinePolygonMode {
		DMK_PIPELINE_POLYGON_MODE_FILL,
		DMK_PIPELINE_POLYGON_MODE_LINE,
		DMK_PIPELINE_POLYGON_MODE_POINT,
		DMK_PIPELINE_POLYGON_MODE_FILL_RECTANGLE,
	};

	enum class DMKPipelineFrontFace {
		DMK_PIPELINE_FRONT_FACE_POSITIVE,
		DMK_PIPELINE_FRONT_FACE_NEGATIVE,
	};

	enum class DMKPipelineMSAASamples {
		DMK_PIPELINE_MSAA_SAMPLES_1,
		DMK_PIPELINE_MSAA_SAMPLES_2,
		DMK_PIPELINE_MSAA_SAMPLES_4,
		DMK_PIPELINE_MSAA_SAMPLES_8,
		DMK_PIPELINE_MSAA_SAMPLES_16,
		DMK_PIPELINE_MSAA_SAMPLES_32,
		DMK_PIPELINE_MSAA_SAMPLES_64,
	};

	enum class DMKSwapChainType {
		DMK_SWAPCHAIN_TYPE_DEFAULT,
		DMK_SWAPCHAIN_TYPE_3D,
		DMK_SWAPCHAIN_TYPE_2D,
		DMK_SWAPCHAIN_TYPE_LIGHTS,
		DMK_SWAPCHAIN_TYPE_OFFSCREEN,
		DMK_SWAPCHAIN_TYPE_COMPUTE,
	};

	enum class DMKRenderPassType {
		DMK_RENDER_PASS_TYPE_DEFAULT,
		DMK_RENDER_PASS_TYPE_3D,
		DMK_RENDER_PASS_TYPE_2D,
	};

	enum class DMKFrameBufferType {
		DMK_FRAME_BUFFER_TYPE_MAIN,
		DMK_FRAME_BUFFER_TYPE_OFFSCREEN
	};
}

#endif // !_DYNAMIK_RENDERING_PIPELINE_SPECIFICATIONS_H
