#pragma once
#ifndef _DYNAMIK_RENDERING_SPECIFICATIONS_H
#define _DYNAMIK_RENDERING_SPECIFICATIONS_H

namespace Dynamik {
	enum class DMKPipelineTopology {
		DMK_PIPELINE_TOPOLOGY_POINT,
		DMK_PIPELINE_TOPOLOGY_LINE_LIST,
		DMK_PIPELINE_TOPOLOGY_LINE_STRIP,
		DMK_PIPELINE_TOPOLOGY_TRIANGLE_LIST,
		DMK_PIPELINE_TOPOLOGY_TRIANGLE_STRIP,
		DMK_PIPELINE_TOPOLOGY_TRIANGLE_FAN,
		DMK_PIPELINE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY,
		DMK_PIPELINE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY,
		DMK_PIPELINE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY,
		DMK_PIPELINE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY,
		DMK_PIPELINE_TOPOLOGY_PATCH_LIST,
	};

	enum class DMKPipelinePolygonMode {
		DMK_PIPELINE_POLYGON_MODE_FILL,
		DMK_PIPELINE_POLYGON_MODE_LINE,
		DMK_PIPELINE_POLYGON_MODE_POINT,
		DMK_PIPELINE_POLYGON_MODE_FILL_RECTANGLE,
	};

	enum class DMKPipelineRasterizerCullMode {
		DMK_PIPELINE_RASTERIZER_CULL_MODE_FRONT,
		DMK_PIPELINE_RASTERIZER_CULL_MODE_BACK,
		DMK_PIPELINE_RASTERIZER_CULL_MODE_FRONT_AND_BACK
	};

	enum class DMKPipelineFrontFace {
		DMK_PIPELINE_FRONT_FACE_POSITIVE,
		DMK_PIPELINE_FRONT_FACE_NEGATIVE,
	};

	enum class DMKPipelineMSAASamples {
		DMK_PIPELINE_MSAA_SAMPLES_1,
		DMK_PIPELINE_MSAA_SAMPLES_2,
		DMK_PIPELINE_MSAA_SAMPLES_4,
		DMK_PIPELINE_MSAA_SAMPLES_8,
		DMK_PIPELINE_MSAA_SAMPLES_16,
		DMK_PIPELINE_MSAA_SAMPLES_32,
		DMK_PIPELINE_MSAA_SAMPLES_64,
	};

	enum class DMKPipelineCompareOP {
		DMK_PIPELINE_COMPARE_OP_NEVER,
		DMK_PIPELINE_COMPARE_OP_LESS,
		DMK_PIPELINE_COMPARE_OP_EQUAL,
		DMK_PIPELINE_COMPARE_OP_LESS_OR_EQUAL,
		DMK_PIPELINE_COMPARE_OP_GRATER,
		DMK_PIPELINE_COMPARE_OP_NOT_EQUAL,
		DMK_PIPELINE_COMPARE_OP_GRATER_OR_NOT_EQUAL,
		DMK_PIPELINE_COMPARE_OP_ALWAYS,
	};

	struct DMKRenderingPipelineDescription {
		DMKPipelineTopology pipelineTopology = DMKPipelineTopology::DMK_PIPELINE_TOPOLOGY_TRIANGLE_LIST;
		UI32 viewPortCount = 1;
		UI32 scissorCount = 1;

		DMKPipelinePolygonMode polygonMode = DMKPipelinePolygonMode::DMK_PIPELINE_POLYGON_MODE_FILL;
		DMKPipelineRasterizerCullMode cullMode = DMKPipelineRasterizerCullMode::DMK_PIPELINE_RASTERIZER_CULL_MODE_FRONT;

		DMKPipelineMSAASamples msaaSamples = DMKPipelineMSAASamples::DMK_PIPELINE_MSAA_SAMPLES_1;

		B1 enableDepthStencil = true;
		B1 enableDepthTest = false;
		DMKPipelineCompareOP compareOP = DMKPipelineCompareOP::DMK_PIPELINE_COMPARE_OP_LESS;

		B1 enableDynamicState = false;
	};
}

#endif // !_DYNAMIK_RENDERING_PIPELINE_SPECIFICATIONS_H
